name = "Potts"
uuid = "6add209f-8b80-4b6d-bc64-86d6ecc52c89"
version = "0.1.0"
authors = ["hacker"]

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
Attractors = "f3fd9213-ca85-4dba-9dfd-7fc91308fec7"
Bijections = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AMRVW = "1.2.1"
Attractors = "1.7.1"
Bijections = "0.2.2"
CairoMakie = "0.15.8"
FromFile = "0.1.6"
JSON = "1.3.0"
LinearAlgebra = "1.12.0"
Plots = "1.41.3"
PolynomialRoots = "1.0.0"
Polynomials = "4.1.0"
ProgressLogging = "0.1.6"
Random = "1.11.0"
